### ISSUE TITLE
Feature request: method of manually running migrations

### ISSUE THREAD

**Issue by pat2man** [Ticketfly/play-liquibase#1]
Sometimes it is important to run database migrations before launching an application. It should be possible to do the following:

1. Set ```liquibase.enable = false```.
2. Run a script, ```bin/apply_migrations``` for example.
3. Start the application.

This would be similar to the ```grails dbm-update``` command.

**Comment by dragisak** [comment]
Maybe have a standalone App that you can invoke from command line ?
Something like: `java -cp <claspath> RunLiquibaseMigrations <options>`

**Comment by guytish** [comment]
I agree with @pat2man - activator liquibase:update should run the migrations. What do you think guys?

**Comment by dragisak** [comment]
This is intended to be a replacement for Play evolutions. There are already a few SBT plugins that do what you want @guytish and @pat2man . For example https://github.com/sbtliquibase/sbt-liquibase-plugin

**Comment by jtescher** [comment]
Sounds like this is a won't fix for now. We can always re-open if we want to evaluate again later.
