### ISSUE TITLE
load files from classpath

### ISSUE THREAD

**Issue by davidschneider** [Ticketfly/play-liquibase#11]
hi

i saw the comment in PlayLiquibaseModule about the classpath loader not working.  however, i think my use case is a little different

i have a sub module with my data access code.  i also have unit tests here which need to run liquibase changes before running the tests.  if i put my liquibase files in my sub module i can use them for my tests and also with the classpath loader from the plugin without errors (they would ultimately be in a jar)

anyhoo, i've already made the basic changes on my fork, but i want to make sure, given the comments, that a pull request would be accept before i finish it up

let me know and i can finish it up real quick

**Comment by dragisak** [comment]
That's what I observed when I tested it with Play 2.4 and Liquibase 3.4. If you created Play distribution archive and run Play from there, you will end up having files from config directory both in the jar, as well as in the distribution config dir. Haven't tried with newer version of Play/Liquibase. 

If nothing works, we can add a config option to switch between class path loader and filesystem loader.

**Comment by dragisak** [comment]
I just looked around and discovered this sbt flag:
```scala
PlayKeys.externalizeResources := false
```

Might be worth testing with classpath loader.

**Comment by davidschneider** [comment]
i think this is the case only when you have your liquibase files in the conf directory of your play app.  in my case, i have another library, which is a dependency of the play app, and my liquibase files are there.  when built, the files would only be in the jar of that library


________________________________

**Comment by davidschneider** [comment]
solid.  can you let me know when its published?

**Comment by dragisak** [comment]
@davidschneider Can you give it a try ? I've published a snapshot:

```scala
resolvers += "Sonatype Snapshots" at Resolver.SonatypeRepositoryRoot + "/snapshots"
libraryDependencies += "com.ticketfly" %% "play-liquibase" % "1.3-SNAPSHOT"
```

**Comment by davidschneider** [comment]
test file and classpath successfully


________________________________

**Comment by dragisak** [comment]
Ok. Version 1.3 should show up on Maven in 10-15 min
