### ISSUE TITLE
play-liquibase doesn't start if user/pass aren't specified

### ISSUE THREAD

**Issue by ashleymercer** [Ticketfly/play-liquibase#14]
Hi there,

This is a great plugin and I find it enormously useful - thanks! 

However, I've found one small quirk that stumped me for a while: if I'm running play locally, I use H2 in-memory as my database and I configure this without a username and password for simplicity. When play-liquibase is starting up, however, it expects there to be values:

https://github.com/Ticketfly/play-liquibase/blob/43534a98f4632fce08336a854807cb45514d4501/play-liquibase/src/main/scala/com/ticketfly/play/liquibase/PlayLiquibaseModule.scala#L104

If user or password are blank, then the for/yield below returns None which results in the (slightly misleading) error "Liquibase is not configured". Can be reproduced with the following in application.conf:

```
slick.dbs.default.driver="slick.driver.H2Driver$"
slick.dbs.default.db.driver="org.h2.Driver"
slick.dbs.default.db.url="jdbc:h2:mem:default;DB_CLOSE_DELAY=-1"

liquibase=${slick.dbs.default.db}
```

**Comment by dragisak** [comment]
Thank you for reporting this. Until I fix this, can you use "sa"/"sa" for username/password ?

**Comment by ashleymercer** [comment]
Thanks for the quick response. Yes, adding a dummy username and password works fine, so I can use this for now :)
