### ISSUE TITLE
Upgrade liquibase-core

### ISSUE THREAD

**Issue by jtescher** [Ticketfly/play-liquibase#3]
Looks like `liquibase-core` is at 3.4.x now: http://www.liquibase.org/download/

**Comment by dragisak** [comment]
I published the snapshot. Can you give it a try ?
```scala
resolvers += Resolver.sonatypeRepo("snapshots")
libraryDependencies +=   "com.ticketfly" %% "play-liquibase" % "0.4-SNAPSHOT"
```

**Comment by jtescher** [comment]
Yep tested it in on: https://github.com/jtescher/play-api and it works with the snapshot :+1:
