### ISSUE TITLE
Regression in Liquibase 3.4.2 prevents UUID generation in MySQL

### ISSUE THREAD

**Issue by pzuraq** [Ticketfly/play-liquibase#7]
There's a regression in Liquibase 3.4.2 that causes it to generate a LONGBLOB for binaries in MySQL. This will prevent us from using for projects that utilize UUIDs: 

http://stackoverflow.com/questions/34493940/liquibase-generates-type-longblob-in-mysql-for-binary16-when-moving-to-springb

**Comment by jtescher** [comment]
😢

**Comment by pzuraq** [comment]
Also, there are no tags for versions on this library. Makes it very hard to figure out which is the last version that would be usable.

**Comment by dragisak** [comment]
Liquibase 3.5.0 seems to be out. Can you check if they have fix for this ?

**Comment by dragisak** [comment]
Looks like it's fixed https://liquibase.jira.com/browse/CORE-2531

**Comment by dragisak** [comment]
Would one of you care to create a pull request ?

**Comment by dragisak** [comment]
Liquibase 3.5.0 release notes: http://www.liquibase.org/2016/04/liquibase-3-5-0-released.html
